<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>PersonalWiki</AssemblyName>
    <RootNamespace>PersonalWiki</RootNamespace>
    <Version>1.0.0</Version>
    <Product>Personal Wiki</Product>
  </PropertyGroup>

</Project>
